<?php
$renderedHeaders = '';
$prefix = '';

foreach ($requestData->getHeaders() as $key => $headers) {
    foreach ($headers as $value) {
        $renderedHeaders .= $prefix . $key . ': ' . $value;

        $prefix = "\r\n";
    }
}

$customMethod = '';
if (!in_array($requestData->getMethod(), ['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'TRACE', 'OPTIONS', 'CONNECT', 'PATCH'], true)) {
    $customMethod = $requestData->getMethod();
}

$version = '1.1';
if (in_array($requestData->getVersion(), ['1.0', '1.1'])) {
    $version = $requestData->getVersion();
}

?>

<form action="/" method="post">
    <div class="form-group">
        <label>URI</label>
        <input type="url" name="uri" placeholder="URI to which to make the request" value="<?php echo htmlspecialchars($requestData->getUri(), ENT_QUOTES | ENT_SUBSTITUTE); ?>">
    </div>
    <div class="form-group">
        <label>HTTP version</label>
        <select name="version">
            <option value="1.0" <?php if ($version === '1.0') echo 'selected="selected"'; ?>>1.0</option>
            <option value="1.1" <?php if ($version === '1.1') echo 'selected="selected"'; ?>>1.1</option>
        </select>
    </div>
    <div class="form-group">
        <label>Method</label>
        <select name="method">
            <option value="GET" <?php if ($requestData->getMethod() === 'GET') echo 'selected="selected"'; ?>>GET</option>
            <option value="HEAD" <?php if ($requestData->getMethod() === 'HEAD') echo 'selected="selected"'; ?>>HEAD</option>
            <option value="POST" <?php if ($requestData->getMethod() === 'POST') echo 'selected="selected"'; ?>>POST</option>
            <option value="PUT" <?php if ($requestData->getMethod() === 'PUT') echo 'selected="selected"'; ?>>PUT</option>
            <option value="DELETE" <?php if ($requestData->getMethod() === 'DELETE') echo 'selected="selected"'; ?>>DELETE</option>
            <option value="TRACE" <?php if ($requestData->getMethod() === 'TRACE') echo 'selected="selected"'; ?>>TRACE</option>
            <option value="OPTIONS" <?php if ($requestData->getMethod() === 'OPTIONS') echo 'selected="selected"'; ?>>OPTIONS</option>
            <option value="CONNECT" <?php if ($requestData->getMethod() === 'CONNECT') echo 'selected="selected"'; ?>>CONNECT</option>
            <option value="PATCH" <?php if ($requestData->getMethod() === 'PATCH') echo 'selected="selected"'; ?>>PATCH</option>
        </select>
    </div>
    <div class="form-group">
        <label>Custom method</label>
        <input type="text" name="custommethod" placeholder="Don't fill when using one of the  default methods" value="<?php echo htmlspecialchars($customMethod, ENT_QUOTES | ENT_SUBSTITUTE); ?>">
    </div>
    <div class="form-group">
        <label>Follow redirects</label>
        <label class="block"><input type="checkbox" name="follow" <?php if ($requestData->redirectsEnabled()) echo 'checked="checked"'; ?> value="true"> Automatically follow redirects?</label>
    </div>
    <div class="form-group">
        <label>Enable cookies</label>
        <label class="block"><input type="checkbox" name="cookies" <?php if ($requestData->cookiesEnabled()) echo 'checked="checked"'; ?> value="true"> Enable cookie storage?</label>
    </div>
    <div class="form-group">
        <label>Request headers (1 per line)</label>
        <textarea name="headers" placeholder="Enter the headers of the request separated by a newline"><?php echo htmlspecialchars($renderedHeaders, ENT_QUOTES | ENT_SUBSTITUTE); ?></textarea>
    </div>
    <div class="form-group">
        <label>Request body</label>
        <textarea name="body" placeholder="Enter the body of the request"><?php echo htmlspecialchars($requestData->getBody(), ENT_QUOTES | ENT_SUBSTITUTE); ?></textarea>
    </div>
    <div class="form-group">
        <label>SSL peer verification</label>
        <label class="block"><input type="checkbox" name="verifypeer" <?php if ($requestData->verifyPeer()) echo 'checked="checked"'; ?> value="true"> Verifying the peer's certificate?</label>
    </div>
    <div class="form-group">
        <label>SSL host verification</label>
        <label class="block"><input type="checkbox" name="verifyhost" <?php if ($requestData->verifyHost()) echo 'checked="checked"'; ?> value="true"> Check the existence of a common name and also verify that it matches the hostname provided?</label>
    </div>
    <div class="form-group">
        <label>SSL version</label>
        <select name="sslversion">
            <option value="automatic">Automatic</option>
            <option value="2" <?php if ($requestData->getSslVersion() === '2') echo 'selected="selected"'; ?>>2</option>
            <option value="3" <?php if ($requestData->getSslVersion() === '3') echo 'selected="selected"'; ?>>3</option>
        </select>
    </div>
    <input type="submit" name="submit" value="Make request">
</form>

<?php if (isset($result)) echo $result; ?>
