<form action="/" method="post">
    <div class="form-group">
        <label>URI</label>
        <input type="url" name="uri" placeholder="URI to which to make the request" value="<?php echo $request->post('uri'); ?>">
    </div>
    <div class="form-group">
        <label>Method</label>
        <select name="method">
            <option value="GET" <?php if ($request->post('method') === 'GET' ) echo 'selected="selected"'; ?>>GET</option>
            <option value="HEAD" <?php if ($request->post('method') === 'HEAD' ) echo 'selected="selected"'; ?>>HEAD</option>
            <option value="POST" <?php if ($request->post('method') === 'POST' ) echo 'selected="selected"'; ?>>POST</option>
            <option value="PUT" <?php if ($request->post('method') === 'PUT' ) echo 'selected="selected"'; ?>>PUT</option>
            <option value="DELETE" <?php if ($request->post('method') === 'DELETE' ) echo 'selected="selected"'; ?>>DELETE</option>
            <option value="TRACE" <?php if ($request->post('method') === 'TRACE' ) echo 'selected="selected"'; ?>>TRACE</option>
            <option value="OPTIONS" <?php if ($request->post('method') === 'OPTIONS' ) echo 'selected="selected"'; ?>>OPTIONS</option>
            <option value="CONNECT" <?php if ($request->post('method') === 'CONNECT' ) echo 'selected="selected"'; ?>>CONNECT</option>
            <option value="PATCH" <?php if ($request->post('method') === 'PATCH' ) echo 'selected="selected"'; ?>>PATCH</option>
        </select>
    </div>
    <div class="form-group">
        <label>Custom method</label>
        <input type="text" name="custommethod" placeholder="Don't fill when using one of the  default methods" value="<?php echo $request->post('custommethod'); ?>">
    </div>
    <div class="form-group">
        <label>Follow redirects</label>
        <label class="block"><input type="checkbox" name="follow" <?php if ($request->post('follow') === 'true' ) echo 'checked="checked"'; ?> value="true"> Automatically follow redirects?</label>
    </div>
    <div class="form-group">
        <label>Enable cookies</label>
        <label class="block"><input type="checkbox" name="cookies" <?php if ($request->post('cookies') === 'true' ) echo 'checked="checked"'; ?> value="true"> Enable cookie storage?</label>
    </div>
    <div class="form-group">
        <label>Request headers (1 per line)</label>
        <textarea name="headers" placeholder="Enter the headers of the request separated by a newline"><?php echo $request->post('headers'); ?></textarea>
    </div>
    <div class="form-group">
        <label>Request body</label>
        <textarea name="body" placeholder="Enter the body of the request"><?php echo $request->post('body'); ?></textarea>
    </div>
    <input type="submit" name="submit" value="Make request">
</form>

<?php if (isset($result)) echo $result; ?>
