<!DOCTYPE html>
<html>
    <head>
        <title>Requestable - Request that shit</title>
        <meta charset="utf-8">
        <script>'article aside footer header nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
        <link href="/style/style.css" rel="stylesheet" type="text/css" media="screen">
    </head>
    <body>
        <header>
            <div class="content">
                <h1><a href="/">Requestable</a></h1>
                <h2>Request that shit</h2>
            </div>
        </header>
        <div id="body">
            <div class="content">
                <?php echo $content; ?>
            </div>
        </div>
        <footer>
            <div class="content">
                <p>Requestable is an <a href="http://github.com/PeeHaa/Requestable" target="_blank">open source</a> project created and maintained by <a href="https://pieterhordijk.com" target="_blank">Pieter Hordijk</a> (<a href="https://github.com/PeeHaa" target="_blank">PeeHaa</a>). Special thanks to Chris Wright (<a href="https://github.com/DaveRandom" target="_blank">DaveRandom</a>).</p>
            </div>
        </footer>
        <script src="/js/main.js"></script>
    </body>
</html>
