<?php
$byteFormatter = new \Requestable\Format\Byte;
?>
<div class="main-content">
    <h1>Recent requests</h1>
    <h2>Showing 100 latest requests sorted by timestamp descending</h2>
    <table>
        <thead>
            <tr>
                <th class="id">#</th>
                <th>URI</th>
                <th class="right version">Version</th>
                <th class="method">Method</th>
                <th class="center follow">Follow</th>
                <th class="center cookies">Cookies</th>
                <th class="right body">Body</th>
                <th class="right headers">Headers</th>
            </tr>
        </thead>
        <?php if ($recentRequests) { ?>
            <tbody>
            <?php foreach ($recentRequests as $id => $storedRequest) { ?>
                <?php if ($storedRequest->getPassword()) continue; ?>
                <tr>
                    <td class="id"><a href="/<?php echo $identifier->toHash($id); ?>"><?php echo $identifier->toHash($id); ?></a></td>
                    <td title="<?php echo htmlspecialchars($storedRequest->getUri()); ?>"><?php echo htmlspecialchars($storedRequest->getUri()); ?></td>
                    <td class="right version"><?php echo htmlspecialchars($storedRequest->getVersion(), ENT_QUOTES | ENT_SUBSTITUTE); ?></td>
                    <td class="method"><?php echo htmlspecialchars($storedRequest->getMethod(), ENT_QUOTES | ENT_SUBSTITUTE); ?></td>
                    <td class="center follow"><input type="checkbox" disabled <?php if ($storedRequest->redirectsEnabled()) echo 'checked'; ?>></td>
                    <td class="center cookies"><input type="checkbox" disabled <?php if ($storedRequest->cookiesEnabled()) echo 'checked'; ?>></td>
                    <td class="right body"><?php echo $byteFormatter->format(strlen($storedRequest->getBody())); ?></td>
                    <td class="right headers">N/A</td>
                </tr>
            <?php } ?>
            </tbody>
        <?php } ?>
    </table>
</div>
