<?php
$byteFormatter = new \Requestable\Format\Byte;
?>
<div class="main-content">
    <h1>Recent requests</h1>
    <h2>Showing 100 latest requests sorted by timestamp descending</h2>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>URI</th>
                <th class="right">Version</th>
                <th>Method</th>
                <th class="center">Follow</th>
                <th class="center">Cookies</th>
                <th class="right">Body</th>
                <th class="right">Headers</th>
            </tr>
        </thead>
        <?php if ($recentRequests) { ?>
            <?php foreach ($recentRequests as $id => $storedRequest) { ?>
                <tbody>
                    <tr>
                        <td><a href="/<?php echo $identifier->toHash($id); ?>"><?php echo $identifier->toHash($id); ?></a></td>
                        <td><?php echo htmlspecialchars($storedRequest->getUri()); ?></td>
                        <td class="right"><?php echo $storedRequest->getVersion(); ?></td>
                        <td><?php echo $storedRequest->getMethod(); ?></td>
                        <td class="center"><input type="checkbox" disabled <?php if ($storedRequest->redirectsEnabled()) echo 'checked'; ?>></td>
                        <td class="center"><input type="checkbox" disabled <?php if ($storedRequest->cookiesEnabled()) echo 'checked'; ?>></td>
                        <td class="right"><?php echo $byteFormatter->format(strlen($storedRequest->getBody())); ?></td>
                        <td class="right">N/A</td>
                    </tr>
                </tbody>
            <?php } ?>
        <?php } ?>
    </table>
</div>
